name: thetamedbot
description: ThetaMedBot.
version: 0.0.1-pre+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  introduction_screen: ^1.0.9
  google_fonts: ^1.1.1
  provider: ^4.3.2+3
  firebase_core: ^0.5.3
  cloud_firestore: ^0.14.4
  firebase_auth: ^0.18.4+1
  tflite: ^1.1.1
  firebase_storage: ^5.2.0
  image_picker: ^0.6.7+15
  shared_preferences: ^0.5.12+4
  connectivity: ^2.0.2
  fancy_bottom_bar: ^0.0.1
  nice_button: ^0.1.7
  url_launcher: ^5.7.10
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/