name: thetamedbot
description: ThetaMedBot.
version: 0.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  introduction_screen: ^1.0.9
  google_fonts: ^1.1.1
  provider: ^4.3.2+2
  firebase_core: ^0.5.2
  cloud_firestore: ^0.14.3
  cloud_functions: ^0.7.0+1
  firebase_database: ^4.3.0
  firebase_auth: ^0.18.3
  tflite: ^1.1.1
  firebase_storage: ^5.0.1
  image_picker: ^0.6.7+14
  shared_preferences: ^0.5.12+4
  font_awesome_flutter: ^8.10.0
  animations: ^1.1.2
  connectivity: ^2.0.1
  built_collection: ^4.3.2
  built_value: ^7.1.0
  fancy_bottom_bar: ^0.0.1
  salomon_bottom_bar: ^2.0.0
  nice_button: ^0.1.7
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  built_value_generator: ^7.1.0
  mockito: ^4.1.3
  flutter_driver:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true
  assets:
    - assets/